# Generated by Django 5.1.6 on 2025-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0005_alter_product_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='link',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
