# Generated by Django 5.1.6 on 2025-05-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0007_category_remove_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_url',
        ),
    ]
