# Generated by Django 5.1.6 on 2025-03-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_customuser_birth_date_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
