# Generated by Django 5.1.6 on 2025-03-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
