# Generated by Django 5.1.6 on 2025-03-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20, unique=True, verbose_name='ID')),
                ('market_place', models.CharField(max_length=50, verbose_name='Market Place')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Характеристики и описание')),
                ('image_url', models.URLField(max_length=500, verbose_name='Фото')),
                ('product_url', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('parsed_at', models.DateTimeField(verbose_name='Дата парсинга')),
            ],
        ),
    ]
