# Generated by Django 5.1.6 on 2025-03-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
