# Generated by Django 5.1.6 on 2025-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_remove_product_id_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parsed_at',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Категория', max_length=255, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(default='Под Категория', max_length=255, verbose_name='Под Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='описание', verbose_name='Характеристики и описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='Photo', max_length=500, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='market_place',
            field=models.CharField(default='Kaspi', max_length=50, verbose_name='Market Place'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Name', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(default='Link', max_length=500, verbose_name='Сылка'),
        ),
    ]
