# Generated by Django 5.1.6 on 2025-05-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_remove_product_parsed_at_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
